# Generated by Django 5.1.6 on 2025-03-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='game_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='gamesessiontrack',
            name='revealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesessiontrack',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Hint',
        ),
    ]
