# Generated by Django 5.0.11 on 2025-02-01 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamesessiontrack',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_tracks', to='games.gamesession'),
        ),
        migrations.AddField(
            model_name='hint',
            name='game_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='games.gamesession'),
        ),
        migrations.AddField(
            model_name='gamesessiontrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.racetrack'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='tracks',
            field=models.ManyToManyField(through='games.GameSessionTrack', to='games.racetrack'),
        ),
        migrations.AlterUniqueTogether(
            name='gamesessiontrack',
            unique_together={('session', 'track')},
        ),
    ]
