# Generated by Django 5.1.6 on 2025-06-12 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gamesession_game_type_gamesessiontrack_revealed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesessiontrack',
            name='submitted_track',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_track', to='games.racetrack'),
        ),
    ]
