# Generated by Django 5.1.6 on 2025-07-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_gamesessiontrack_submitted_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='tracks',
        ),
    ]
